[package]
name = "numerator"
version = "0.1.0"
edition = "2021"
default-run = "numerotator" 

[[bin]]
name = "numerotator"
path = "src/main.rs"

[[bin]]
name = "install"
path = "src/install.rs"

[dependencies]
bio = "1.3.1"
clap = { version = "4.4.0", features = ["derive"] }
itertools = "0.10.5"
